engagementSurvey/urls.py
from django.urls import path
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
]

app_name = 'engagementSurvey'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name ='new'),
    path('<str:company_name>/results/', views.results, name='results'),
    path('<str:company_name>/export/', views.export_answers_csv, name='export_answers_csv'),
    path('<str:company_name>/<str:secret_id>/', views.landing, name = 'landing'),
    path('<str:company_name>/<str:secret_id>/survey/', views.survey, name = 'survey'),
    path('<str:company_name>/<str:secret_id>/thanks/', views.thanks, name = 'thanks'),
    path('<str:company_name>/<str:secret_id>/submit/', views.submit, name ='submit'),
]

surveyProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from django.contrib.auth import views


urlpatterns = [
	path('polls/', include('polls.urls')),
	path('engagementSurvey/', include('engagementSurvey.urls')),
    path('admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
]

engagementSurvey/models.py
from django.db import models

import uuid

# Create your models here.

class Question(models.Model):
    question_id = models.CharField(max_length=36,primary_key=True, default=str(uuid.uuid1()), editable=False)
    question_text = models.CharField(max_length = 200)
    question_detail = models.CharField(max_length = 200, blank=True)
    default_text = models.CharField(max_length = 50, default = "Add additional info")

    QUESTION_TYPES = ( #could have these as subclasses
        ('G','1-7 Gallup'),
        ('GP','1-7 Gallup with text box'),
        ('TB','Text box'),
        ('SO','Single option'),
        ('MO','Multiple option'),
    )
    question_type = models.CharField(max_length=2, choices=QUESTION_TYPES, default = 'G')

    def __str__(self):
        return self.question_text

    class Meta:
        ordering = ['question_type','question_text']

class Company(models.Model):
    cid = models.CharField(max_length=36, primary_key=True, default=str(uuid.uuid1()), editable=False)
    company_name =  models.CharField(max_length = 50)
    company_code = models.CharField(max_length = 2, unique=True)
    num_employees = models.IntegerField()
    questions = models.ManyToManyField(Question, blank=True)
    responses = models.ManyToManyField('Answer', blank=True)
    employees = models.ManyToManyField('Employee', blank=True, related_name='+')

    class Meta:
        verbose_name_plural = "Companies"
        ordering = ['company_name']
    
    def __str__(self):
        return self.company_name



class Employee(models.Model):
    eid = models.CharField(max_length=36, primary_key=True, default=str(uuid.uuid1()), editable=False)
    secret_id = models.CharField(max_length = 10)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    has_answered = models.BooleanField(default=False)
    answer_time = models.DateTimeField(blank=True, null=True)
    #temporary solution for employee types
    EMPLOYEE_TYPES = (
        ('','- Level -'),
        ('UM','Upper Management'),
        ('MM','Middle Management'),
        ('LM','Lower Management'),
        ('OT','Other'),
    )
    e_type = models.CharField(max_length=2, choices=EMPLOYEE_TYPES, blank=True)

    #temporary solution for company division (add specific ones for companies later)
    EMPLOYEE_AREA = (
        ('','- Department -'),
        ('E','Education'),
        ('HR','Human Resources'),
        ('F','Finance'),
        ('M','Management'),
        ('O','Other'),
    )
    job_area = models.CharField(max_length=2, choices=EMPLOYEE_AREA, blank=True)

    def __str__(self):
        return(self.secret_id)

    class Meta:
        ordering = ['secret_id']


# Many different ways of storing this info. Not sure if best to have own table, or store elsewhere
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    answer_value = models.SmallIntegerField(default=0)
    answer_text = models.CharField(max_length=500, blank=True)
    
    class Meta:
        ordering = ['employee','question']

    def __str__(self):
        return((self.question.__str__()) + " " + self.employee.__str__() + ": " + str(self.answer_value) + ": " + str(self.answer_text))

    #Create new model methods to give easy access to questions and answers?

engagementSurvey/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.Form):
    employee_type = forms.ChoiceField(choices=Employee.EMPLOYEE_TYPES)
    employee_department = forms.ChoiceField(choices=Employee.EMPLOYEE_AREA)

class NewCompanyForm(forms.Form):
    company_name = forms.CharField(max_length = 50)
    company_code = forms.CharField(max_length = 2)
    num_employees = forms.IntegerField()

engagementSurvey/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.urls import reverse
from datetime import datetime
from .forms import EmployeeForm, NewCompanyForm
from django.contrib.auth.decorators import login_required

import uuid
import random
import csv

# Create your views here.

from .models import Question, Company, Answer, Employee

def index(request):
    return HttpResponse("Hello, world. You're at the Engagement Survey Index")

'''
def landing(request,company_name,secret_id):
    company = get_object_or_404(Company, company_name=company_name)
    return render(request, 'engagementSurvey/landing.html', {'company': company})
'''

def survey(request,company_name,secret_id):
    company = get_object_or_404(Company, company_name=company_name)
    company_questions = company.questions.all()
    context = {
        'company_questions': company_questions,
        'company_name': company_name,
        'secret_id': secret_id,
    }
    return render(request, 'engagementSurvey/survey.html', context)

def thanks(request,company_name,secret_id):
    company = get_object_or_404(Company, company_name=company_name)
    return render(request, 'engagementSurvey/thanks.html', {'company_name': company_name})


# All needs changing!
def submit(request, company_name, secret_id):
    company = get_object_or_404(Company, company_name=company_name)
    questions = company.questions.all()
    employee = get_object_or_404(Employee, secret_id=secret_id)

    for question in questions:
        selected_choice = request.POST.get(str(question.question_id), "")
        submitted_answer_text = request.POST.get((str(question.question_id) + '_text'), "")
        if(not(submitted_answer_text == question.default_text)):
            answer = Answer(question=question, employee=employee, answer_value=selected_choice, answer_text=submitted_answer_text, company=company)
        else:
            answer = Answer(question=question, employee=employee, answer_value=selected_choice, company=company)
        answer.save()
        company.responses.add(answer)
        company.save()

    employee.has_answered=True
    employee.answer_time=datetime.now()
    employee.save()

    return HttpResponseRedirect(reverse('engagementSurvey:thanks',args=(company_name,secret_id,))) 

def landing(request,company_name, secret_id):
    
    company = get_object_or_404(Company, company_name=company_name)
    employee = get_object_or_404(Employee, secret_id=secret_id)

    if not(employee.has_answered):
        # if this is a POST request we need to process the form data
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = EmployeeForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required
                employee.e_type = form.cleaned_data['employee_type']
                employee.job_area = form.cleaned_data['employee_department']
                employee.save()
                # redirect to a new URL:
                return HttpResponseRedirect(reverse('engagementSurvey:survey', kwargs=({'company_name' : company_name, 'secret_id': secret_id})))
        # if a GET (or any other method) we'll create a blank form
        else:
            form = EmployeeForm()
        context = {
            'form': form,
            'company_name': company_name,
            'secret_id': secret_id,
            'company': company,
        }
        
        return render(request, 'engagementSurvey/landing.html', context)    
    else:
        return HttpResponse("You've already answered this survey!")
    

@login_required
def results(request, company_name):
    company = get_object_or_404(Company, company_name=company_name)

    company_employees = Employee.objects.filter(company=company)
    company_questions = company.questions.all()
    company_employees_answered = Employee.objects.filter(company=company, has_answered=True)
    company_answers = Answer.objects.filter(company=company)

    company_employees_answered_count = str(len(company_employees_answered)) + "/" + str(len(company_employees))


    context = {
        'company_name': company_name,
        'company_employees': company_employees,
        'company_questions': company_questions,
        'company_employees_answered': company_employees_answered,
        'company_employees_answered_count': company_employees_answered_count,
        'company_answers': company_answers,

    }


    return render(request, 'engagementSurvey/results.html', context)    

def generateSecretId(company_code, employee_number):
    return str(company_code + str(employee_number) + str(random.randint(10000,99999)))

@login_required
def new(request):

    if request.method == 'POST':

        # New Company
        form = NewCompanyForm(request.POST)

        if form.is_valid():
            # process the data in form.cleaned_data as required
            company_name = form.cleaned_data['company_name']
            company_code = form.cleaned_data['company_code']
            num_employees = form.cleaned_data['num_employees']
            cid = str(uuid.uuid4())
            company = Company(company_name = company_name, company_code = company_code, num_employees=num_employees, cid=cid)
            company.save()
            e = 0
            while e < num_employees:
                eid = company_code + str(e)
                secret_id = generateSecretId(company_code,e)
                employee = Employee(eid=str(uuid.uuid4()), secret_id=secret_id, company=company)
                employee.save()
                company.employees.add(employee)
                company.save()
                e += 1

            # redirect to a new URL:
            return HttpResponse("Company " + company_name + " created with " + str(num_employees) + " employees")
        # if a GET (or any other method) we'll create a blank form
        
    else:
        form = NewCompanyForm()

    context = {
        'form': form,
    }
    
    return render(request, 'engagementSurvey/new.html', context)  
    

@login_required
def export_answers_csv(request, company_name):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="'+ company_name + '_answers.csv"'

    writer = csv.writer(response)
    writer.writerow(['Question', 'Employee', 'Value', 'Comment'])
    
    company = get_object_or_404(Company, company_name=company_name)
    answers = Answer.objects.filter(company=company).values_list('question__question_text','employee__secret_id','answer_value','answer_text')
    for answer in answers:
        writer.writerow(answer)

    return response

engagementSurvey/templates/engagementSurvey/base.html
{% load static %}

<html>
	<head>
		<title>{% block title %}HRMP Survey{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
        <link rel="stylesheet" type="text/css" href="{% static 'engagementSurvey/css/main.css' %}" />
        <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
    </head>


        <!-- Header -->
        <section id="three" class="wrapper style2 special">
            <header class="major">
                    <h2> {{company_name}} Employee Engagement Survey</h2>
            </header>
        </section>

    
       

    <body id="top">
        <div class="content">
            

            <section id="two" class="wrapper">
                <div class="inner alt">

                    {% block content %}{% endblock %}
                    
                    <p>Survey run by HRPM</p>

                </div>


            </section>
        </div><br>
    </body><br>
    

</html>

engagementSurvey/templates/engagementSurvey/landing.html
{% extends 'engagementSurvey/base.html' %}
{% block title %}{{ company.company_name }} Survey by HRPM{% endblock %}
{% block content %}

{% if company %}

    <section class="spotlight">

        <!-- <div class="image"><img src='' alt="company-logo" /></div> Company Logo-->
        <div class="content">
            <h3>Welcome to the survey</h3>
            <p>Thank you for taking part in the {{ company.company_name }} employee engagement survey, run by HRPM. All of your answers are confidential and we don't ask you for any personal details. Only anonymous data is sent to {{ company.company_name }} by HRPM.</p>
        </div>
    </section>
    
    <form action="" method="post">
            {% csrf_token %}
            <div class="12u$">
                <div class="select-wrapper">{{ form.employee_type }}</div>
            </div>
            <br>
            <div class="12u$">
                <div class="select-wrapper">{{ form.employee_department }}</div>
            </div>
            <br>
        <input type="submit" value="Submit">
    </form>

{% else %}
    <p>This company doesn't have a survey</p>
{% endif %}


{% endblock %}

engagementSurvey/templates/engagementSurvey/new.html
{% extends 'engagementSurvey/base.html' %}
{% block title %}{{ company.company_name }} Survey Results{% endblock %}
{% block content %}

<form action="{% url 'engagementSurvey:new' %}" method="post">
        {% csrf_token %}
        {{ form }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

engagementSurvey/templates/engagementSurvey/results.html
{% extends 'engagementSurvey/base.html' %}
{% block title %}{{company_name}} Survey Results{% endblock %}
{% block content %}

<header>
    <h2>Survey results for {{company_name}}</h2>
</header>

<div class="row">
    <div class="6u 12u$(medium)">
        <h5>Questions</h5>
        
        <ul>
        {% for question in company_questions %}
        <li>{{question}}</li>
        {% endfor %}
        </ul>
    </div>
    
</div>

<div class="row">

    <div class="6u 12u$(medium)">
            <h5>Employees</h5>
            
            <ul>
            {% for employee in company_employees %}
            <li><a href="/admin/engagementSurvey/employee/{{employee.eid}}/change/">{{employee}}</a></li>
            {% endfor %}
            </ul>
    </div>

    <div class="6u 12u$(medium)">
            <h5>Employees Links</h5>
            
            <ul>
            {% for employee in company_employees %}
            <li><a href="/engagementSurvey/{{company_name}}/{{employee.secret_id}}/">engagementSurvey/{{company_name}}/{{employee.secret_id}}/</a></li>
            {% endfor %}
            </ul>
    </div>

    <div class="6u 12u$(medium)">
            <h5>Employees That Have Answered ({{company_employees_answered_count}})</h5>
            
            <ul>
            {% for employee in company_employees_answered %}
            <li><a href="/admin/engagementSurvey/employee/{{employee.eid}}/change/">{{employee}}</a></li>
            {% endfor %}
            </ul>
    </div>



</div>

    <div class="row">
        <div class="6u 12u$(medium)">
            <h5>Answers</h5>
            
            <ul>
            {% for answer in company_answers %}
            <li>{{answer}}</li>
            {% endfor %}
            </ul>
        </div>
        
    </div>


    <div class="row">
        <div class="6u 12u$(medium)">
            <p>
            <a href="{% url 'engagementSurvey:export_answers_csv' company_name %}">Export all answers</a>
            </p>
        </div>
    </div>


    {% endblock %}

engagementSurvey/templates/engagementSurvey/survey.html
{% extends 'engagementSurvey/base.html' %}
{% block title %}{{ company.company_name }} Survey by HRPM{% endblock %}
{% block content %}

{% if company_questions %}
    <ul>
    
    <form action="{% url 'engagementSurvey:submit' company_name=company_name secret_id=secret_id %}" method="post">
        {% csrf_token %}

        {% for question in company_questions %}
        
            <div class="row uniform">
                <div class="12u$">
                    <h1>{{ question.question_text }}</h2>
                    <p>{{ question.question_detail }}</p>

                    {% if question.question_type == 'G' or question.question_type == 'GP' %}
                        <div class="actions fit small">
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.1" value="1" />
                            <label for="{{ question.question_id }}.1">1</label>
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.2" value="2" />
                            <label for="{{ question.question_id }}.2">2</label>
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.3" value="3" />
                            <label for="{{ question.question_id }}.3">3</label>
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.4" value="4" checked />
                            <label for="{{ question.question_id }}.4">4</label>
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.5" value="5" />
                            <label for="{{ question.question_id }}.5">5</label>
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.6" value="6" />
                            <label for="{{ question.question_id }}.6">6</label>
                            <input type="radio" name="{{ question.question_id }}" id="{{ question.question_id }}.7" value="7" />
                            <label for="{{ question.question_id }}.7">7</label>
                        </div>
                        {% if question.question_type == "GP" %}
                            <textarea rows="4" cols="50" name="{{ question.question_id }}_text" placeholder="{{ question.default_text }}" ></textarea><br>
                        {% endif %}
                    {% elif question.question_type == "TB" %}
                        <textarea rows="4" cols="50" name="{{ question.question_id }}_text">Answer</textarea><br>
                    {% endif %}

                </div>
                
            </div>

            <br>
        {% endfor %}

        <input type="submit" value="Submit Form">
    </form>

</ul>
{% else %}
    <p>This survey doesn't have any questions!</p>
{% endif %}

</html>


{% endblock %}

engagementSurvey/templates/engagementSurvey/thanks.html
{% extends 'engagementSurvey/base.html' %}
{% block title %}{{ company.company_name }} Survey by HRPM{% endblock %}
{% block content %}


{% if company_name %}
    <h1>Thank you for completing the survey!</h1>
{% else %}
    <p>Uh oh</p>
{% endif %}

{% endblock %}